Cleanup post-receive script

diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -9,8 +9,8 @@ set -ex
 ## --- Config
 
 deployDir="../deploy"
-buildConfig="--rm=true"              #could be empty
-runConfig="--restart=unless-stopped" #could be empty -p 49153:3000
+# buildConfig="--rm=true"              #could be empty
+# runConfig="--restart=unless-stopped" #could be empty -p 49153:3000
 
 ## --- End Config
 
@@ -18,8 +18,8 @@ while read oldrev newrev refname; do
     branch=$(git rev-parse --symbolic --abbrev-ref $refname)
     if [ "main" == "$branch" ]; then
 
-        imageName="dnt-discord-bot" #docker img name
-        containerName="$imageName"  #docker container name
+        # imageName="dnt-discord-bot" #docker img name
+        # containerName="$imageName"  #docker container name
 
         lastCommit=$(git log --pretty=format:'%h' -n 1) #get last commit for img tag
 
@@ -29,30 +29,30 @@ while read oldrev newrev refname; do
         cd $deployDir
         cp ../dnt-discord-bot-env .env
 
-        echo "Docker : Building $imageName:$lastCommit"
-        buildID=$(sudo docker build $buildConfig -t $imageName .) # This build and tag the image with "latest" tag
-        sudo docker tag $imageName:latest $imageName:$lastCommit  # Add the commit tag
+        # echo "Docker : Building $imageName:$lastCommit"
+        # buildID=$(sudo docker build $buildConfig -t $imageName .) # This build and tag the image with "latest" tag
+        # sudo docker tag $imageName:latest $imageName:$lastCommit  # Add the commit tag
 
-        if [ $? -ne 0 ]; then
-            echo "Docker : Build failed, aborting"
-            exit 1
-        fi
+        # if [ $? -ne 0 ]; then
+        #     echo "Docker : Build failed, aborting"
+        #     exit 1
+        # fi
 
-        set +e
-        r=$(sudo docker container ls --all | grep $containerName)
-        if [ $? -eq 0 ]; then
-            set -e
-            echo "Docker : stop and rm $containerName"
-            sudo docker stop $containerName
-            sudo docker rm $containerName
-            if [ $? -ne 0 ]; then
-                echo "Docker : Stop failed, aborting"
-                exit 1
-            fi
-        fi
+        # set +e
+        # r=$(sudo docker container ls --all | grep $containerName)
+        # if [ $? -eq 0 ]; then
+        #     set -e
+        #     echo "Docker : stop and rm $containerName"
+        #     sudo docker stop $containerName
+        #     sudo docker rm $containerName
+        #     if [ $? -ne 0 ]; then
+        #         echo "Docker : Stop failed, aborting"
+        #         exit 1
+        #     fi
+        # fi
         set -e
-        echo "Docker : run $containerName"
-        sudo docker compose up
+        echo "Docker : building and running apps"
+        sudo docker compose up --build --detach
 
         if [ $? -ne 0 ]; then
             echo "Docker : Run failed, aborting"
